CREATE DATABASE QuanLySinhVien;
USE QuanLySinhVien;


-- 1. KHỞI TẠO BẢNG KHOAHOC (Lưu trữ danh mục môn học gốc)
CREATE TABLE KHOAHOC (
    MaKhoaHoc VARCHAR(50) NOT NULL,
    TenKhoaHoc VARCHAR(255) NOT NULL,
    MoTa TEXT,
    SoTinChi INT NOT NULL,
    CONSTRAINT PK_KHOAHOC PRIMARY KEY (MaKhoaHoc)
);
-- 2. KHỞI TẠO BẢNG GIANGVIEN (Lưu trữ hồ sơ giảng viên)
CREATE TABLE GIANGVIEN (
    MaGV VARCHAR(50) NOT NULL,
    TenGV VARCHAR(255) NOT NULL,
    BoMon VARCHAR(100),
    Email VARCHAR(100),
    ChuyenNganh VARCHAR(150),
    SoDienThoai VARCHAR(15),
    CONSTRAINT PK_GIANGVIEN PRIMARY KEY (MaGV),
    CONSTRAINT UC_Email_GV UNIQUE (Email)
);

-- 3. KHỞI TẠO BẢNG SINHVIEN (Lưu trữ hồ sơ lý lịch sinh viên)
CREATE TABLE SINHVIEN (
    MaSV VARCHAR(50) NOT NULL,
    HoTen VARCHAR(255) NOT NULL,
    GioiTinh VARCHAR(10),
    NgaySinh DATE,
    NganhHoc VARCHAR(150),
    Email VARCHAR(100),
    SoDienThoai VARCHAR(15),
    DiaChi VARCHAR(255),
    NamNhapHoc INT,
    TrangThaiHocTap VARCHAR(50),
    CONSTRAINT PK_SINHVIEN PRIMARY KEY (MaSV),
    CONSTRAINT UC_Email_SV UNIQUE (Email)
);

-- 4. KHỞI TẠO BẢNG LOPHOCPHAN (Lớp học thực tế triển khai theo kỳ)
CREATE TABLE LOPHOCPHAN (
    MaLHP VARCHAR(50) NOT NULL,
    ThoiGianHoc VARCHAR(100),
    DiaDiemHoc VARCHAR(100),
    MaGV VARCHAR(50),
    MaKhoaHoc VARCHAR(50) NOT NULL,
    CONSTRAINT PK_LOPHOCPHAN PRIMARY KEY (MaLHP),
    CONSTRAINT FK_LHP_GIANGVIEN FOREIGN KEY (MaGV) 
        REFERENCES GIANGVIEN(MaGV) ON DELETE SET NULL,
    CONSTRAINT FK_LHP_KHOAHOC FOREIGN KEY (MaKhoaHoc) 
        REFERENCES KHOAHOC(MaKhoaHoc) ON DELETE CASCADE
);
-- 5. KHỞI TẠO BẢNG KETQUAHOCTAP (Bảng trung gian lưu kết quả điểm số)
CREATE TABLE KETQUAHOCTAP (
    MaSV VARCHAR(50) NOT NULL,
    MaLHP VARCHAR(50) NOT NULL,
    DiemSo DECIMAL(4,2),
    XepLoai VARCHAR(50),
    CONSTRAINT PK_KETQUAHOCTAP PRIMARY KEY (MaSV, MaLHP),
    CONSTRAINT FK_KQ_SINHVIEN FOREIGN KEY (MaSV) 
        REFERENCES SINHVIEN(MaSV) ON DELETE CASCADE,
    CONSTRAINT FK_KQ_LOPHOCPHAN FOREIGN KEY (MaLHP) 
        REFERENCES LOPHOCPHAN(MaLHP) ON DELETE CASCADE
);
-- 6. KHỞI TẠO BẢNG PHUTRACH (Bảng mối quan hệ N:N giữa GV và Khóa Học)
CREATE TABLE PHUTRACH (
    MaGV VARCHAR(50) NOT NULL,
    MaKhoaHoc VARCHAR(50) NOT NULL,
    CONSTRAINT PK_PHUTRACH PRIMARY KEY (MaGV, MaKhoaHoc),
    CONSTRAINT FK_PT_GIANGVIEN FOREIGN KEY (MaGV) 
        REFERENCES GIANGVIEN(MaGV) ON DELETE CASCADE,
    CONSTRAINT FK_PT_KHOAHOC FOREIGN KEY (MaKhoaHoc) 
        REFERENCES KHOAHOC(MaKhoaHoc) ON DELETE CASCADE
);